# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget VTK::WrappingTools VTK::WrapHierarchy VTK::WrapPython VTK::WrapPythonInit VTK::ParseJava VTK::WrapJava VTK::kwiml VTK::vtksys VTK::utf8 VTK::CommonCore VTK::CommonMath VTK::CommonTransforms VTK::CommonMisc VTK::CommonSystem VTK::CommonDataModel VTK::CommonExecutionModel VTK::FiltersCore VTK::CommonColor VTK::CommonComputationalGeometry VTK::FiltersGeneral VTK::FiltersGeometry VTK::FiltersSources VTK::RenderingCore VTK::TestingCore VTK::ImagingCore VTK::DICOMParser VTK::jpeg VTK::zlib VTK::metaio VTK::png VTK::pugixml VTK::tiff VTK::IOImage VTK::TestingRendering VTK::ImagingMath VTK::opengl VTK::RenderingUI VTK::glew VTK::RenderingOpenGL2 VTK::RenderingVolume VTK::RenderingVolumeOpenGL2 VTK::doubleconversion VTK::lz4 VTK::lzma VTK::IOCore VTK::IOPLY VTK::IOLegacy VTK::expat VTK::IOXMLParser VTK::IOXML VTK::ImagingSources VTK::freetype VTK::RenderingFreeType VTK::ImagingFourier VTK::eigen VTK::FiltersStatistics VTK::ParallelCore VTK::diy2 VTK::ParallelDIY VTK::FiltersExtraction VTK::InfovisCore VTK::libxml2 VTK::IOInfovis VTK::FiltersHybrid VTK::jsoncpp VTK::IOGeometry VTK::InteractionStyle VTK::FiltersModeling)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target VTK::WrappingTools
add_library(VTK::WrappingTools STATIC IMPORTED)

set_target_properties(VTK::WrappingTools PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
)

# Create imported target VTK::WrapHierarchy
add_executable(VTK::WrapHierarchy IMPORTED)

# Create imported target VTK::WrapPython
add_executable(VTK::WrapPython IMPORTED)

# Create imported target VTK::WrapPythonInit
add_executable(VTK::WrapPythonInit IMPORTED)

# Create imported target VTK::ParseJava
add_executable(VTK::ParseJava IMPORTED)

# Create imported target VTK::WrapJava
add_executable(VTK::WrapJava IMPORTED)

# Create imported target VTK::kwiml
add_library(VTK::kwiml INTERFACE IMPORTED)

set_target_properties(VTK::kwiml PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::vtksys
add_library(VTK::vtksys STATIC IMPORTED)

set_target_properties(VTK::vtksys PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_LINK_LIBRARIES "dl"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::utf8
add_library(VTK::utf8 INTERFACE IMPORTED)

set_target_properties(VTK::utf8 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::CommonCore
add_library(VTK::CommonCore STATIC IMPORTED)

set_target_properties(VTK::CommonCore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::kwiml;VTK::vtksys;\$<LINK_ONLY:VTK::utf8>;Threads::Threads;\$<LINK_ONLY:\$<\$<PLATFORM_ID:SunOS>:socket>>;\$<LINK_ONLY:\$<\$<PLATFORM_ID:SunOS>:nsl>>;\$<LINK_ONLY:\$<\$<PLATFORM_ID:Android>:log>>"
)

# Create imported target VTK::CommonMath
add_library(VTK::CommonMath STATIC IMPORTED)

set_target_properties(VTK::CommonMath PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore"
)

# Create imported target VTK::CommonTransforms
add_library(VTK::CommonTransforms STATIC IMPORTED)

set_target_properties(VTK::CommonTransforms PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonMath;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::CommonMisc
add_library(VTK::CommonMisc STATIC IMPORTED)

set_target_properties(VTK::CommonMisc PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonMath;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::CommonSystem
add_library(VTK::CommonSystem STATIC IMPORTED)

set_target_properties(VTK::CommonSystem PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;\$<LINK_ONLY:VTK::vtksys>;\$<LINK_ONLY:\$<\$<PLATFORM_ID:WIN32>:wsock32>>;\$<LINK_ONLY:Threads::Threads>"
)

# Create imported target VTK::CommonDataModel
add_library(VTK::CommonDataModel STATIC IMPORTED)

set_target_properties(VTK::CommonDataModel PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonMath;VTK::CommonTransforms;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::CommonExecutionModel
add_library(VTK::CommonExecutionModel STATIC IMPORTED)

set_target_properties(VTK::CommonExecutionModel PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::CommonSystem>"
)

# Create imported target VTK::FiltersCore
add_library(VTK::FiltersCore STATIC IMPORTED)

set_target_properties(VTK::FiltersCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonMisc;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::CommonColor
add_library(VTK::CommonColor STATIC IMPORTED)

set_target_properties(VTK::CommonColor PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel"
)

# Create imported target VTK::CommonComputationalGeometry
add_library(VTK::CommonComputationalGeometry STATIC IMPORTED)

set_target_properties(VTK::CommonComputationalGeometry PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel"
)

# Create imported target VTK::FiltersGeneral
add_library(VTK::FiltersGeneral STATIC IMPORTED)

set_target_properties(VTK::FiltersGeneral PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonMisc;VTK::FiltersCore;\$<LINK_ONLY:VTK::CommonComputationalGeometry>;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>"
)

# Create imported target VTK::FiltersGeometry
add_library(VTK::FiltersGeometry STATIC IMPORTED)

set_target_properties(VTK::FiltersGeometry PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::FiltersCore>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::FiltersSources
add_library(VTK::FiltersSources STATIC IMPORTED)

set_target_properties(VTK::FiltersSources PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonDataModel;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonComputationalGeometry>;\$<LINK_ONLY:VTK::CommonCore>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::FiltersCore>;\$<LINK_ONLY:VTK::FiltersGeneral>"
)

# Create imported target VTK::RenderingCore
add_library(VTK::RenderingCore STATIC IMPORTED)

set_target_properties(VTK::RenderingCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonMath;VTK::FiltersCore;\$<LINK_ONLY:VTK::CommonColor>;\$<LINK_ONLY:VTK::CommonComputationalGeometry>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::FiltersGeneral>;\$<LINK_ONLY:VTK::FiltersGeometry>;\$<LINK_ONLY:VTK::FiltersSources>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::TestingCore
add_library(VTK::TestingCore INTERFACE IMPORTED)

set_target_properties(VTK::TestingCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::vtksys"
)

# Create imported target VTK::ImagingCore
add_library(VTK::ImagingCore STATIC IMPORTED)

set_target_properties(VTK::ImagingCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonTransforms>"
)

# Create imported target VTK::DICOMParser
add_library(VTK::DICOMParser STATIC IMPORTED)

set_target_properties(VTK::DICOMParser PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::jpeg
add_library(VTK::jpeg STATIC IMPORTED)

set_target_properties(VTK::jpeg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::zlib
add_library(VTK::zlib STATIC IMPORTED)

set_target_properties(VTK::zlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::metaio
add_library(VTK::metaio STATIC IMPORTED)

set_target_properties(VTK::metaio PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::zlib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::png
add_library(VTK::png STATIC IMPORTED)

set_target_properties(VTK::png PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_LINK_LIBRARIES "VTK::zlib;\$<LINK_ONLY:m>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::pugixml
add_library(VTK::pugixml STATIC IMPORTED)

set_target_properties(VTK::pugixml PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::tiff
add_library(VTK::tiff STATIC IMPORTED)

set_target_properties(VTK::tiff PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:VTK::jpeg>;\$<LINK_ONLY:VTK::zlib>"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::IOImage
add_library(VTK::IOImage STATIC IMPORTED)

set_target_properties(VTK::IOImage PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonExecutionModel;VTK::ImagingCore;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::DICOMParser>;\$<LINK_ONLY:VTK::jpeg>;\$<LINK_ONLY:VTK::metaio>;\$<LINK_ONLY:VTK::png>;\$<LINK_ONLY:VTK::pugixml>;\$<LINK_ONLY:VTK::tiff>;\$<LINK_ONLY:VTK::vtksys>;\$<LINK_ONLY:VTK::zlib>"
)

# Create imported target VTK::TestingRendering
add_library(VTK::TestingRendering STATIC IMPORTED)

set_target_properties(VTK::TestingRendering PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::RenderingCore;VTK::TestingCore;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonExecutionModel>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::IOImage>;\$<LINK_ONLY:VTK::ImagingCore>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::ImagingMath
add_library(VTK::ImagingMath STATIC IMPORTED)

set_target_properties(VTK::ImagingMath PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonCore>;\$<LINK_ONLY:VTK::CommonDataModel>"
)

# Create imported target VTK::opengl
add_library(VTK::opengl INTERFACE IMPORTED)

set_target_properties(VTK::opengl PROPERTIES
  INTERFACE_LINK_LIBRARIES "OpenGL::GLES3;OpenGL::EGL"
)

# Create imported target VTK::RenderingUI
add_library(VTK::RenderingUI STATIC IMPORTED)

set_target_properties(VTK::RenderingUI PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::RenderingCore;\$<LINK_ONLY:android>"
)

# Create imported target VTK::glew
add_library(VTK::glew STATIC IMPORTED)

set_target_properties(VTK::glew PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "GLEW_STATIC"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_LINK_LIBRARIES "VTK::opengl"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::RenderingOpenGL2
add_library(VTK::RenderingOpenGL2 STATIC IMPORTED)

set_target_properties(VTK::RenderingOpenGL2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::RenderingCore;VTK::RenderingUI;VTK::glew;\$<LINK_ONLY:VTK::CommonExecutionModel>;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::opengl>;\$<LINK_ONLY:VTK::vtksys>;\$<LINK_ONLY:android>"
)

# Create imported target VTK::RenderingVolume
add_library(VTK::RenderingVolume STATIC IMPORTED)

set_target_properties(VTK::RenderingVolume PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonExecutionModel;VTK::RenderingCore;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::ImagingCore>"
)

# Create imported target VTK::RenderingVolumeOpenGL2
add_library(VTK::RenderingVolumeOpenGL2 STATIC IMPORTED)

set_target_properties(VTK::RenderingVolumeOpenGL2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::ImagingCore;VTK::ImagingMath;VTK::RenderingCore;VTK::RenderingOpenGL2;VTK::RenderingVolume;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::FiltersCore>;\$<LINK_ONLY:VTK::FiltersGeneral>;\$<LINK_ONLY:VTK::FiltersSources>;\$<LINK_ONLY:VTK::glew>;\$<LINK_ONLY:VTK::opengl>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::doubleconversion
add_library(VTK::doubleconversion STATIC IMPORTED)

set_target_properties(VTK::doubleconversion PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::lz4
add_library(VTK::lz4 STATIC IMPORTED)

set_target_properties(VTK::lz4 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::lzma
add_library(VTK::lzma STATIC IMPORTED)

set_target_properties(VTK::lzma PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::IOCore
add_library(VTK::IOCore STATIC IMPORTED)

set_target_properties(VTK::IOCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::doubleconversion>;\$<LINK_ONLY:VTK::lz4>;\$<LINK_ONLY:VTK::lzma>;\$<LINK_ONLY:VTK::utf8>;\$<LINK_ONLY:VTK::vtksys>;\$<LINK_ONLY:VTK::zlib>"
)

# Create imported target VTK::IOPLY
add_library(VTK::IOPLY STATIC IMPORTED)

set_target_properties(VTK::IOPLY PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::IOCore;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::IOLegacy
add_library(VTK::IOLegacy STATIC IMPORTED)

set_target_properties(VTK::IOLegacy PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::IOCore;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::expat
add_library(VTK::expat STATIC IMPORTED)

set_target_properties(VTK::expat PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::IOXMLParser
add_library(VTK::IOXMLParser STATIC IMPORTED)

set_target_properties(VTK::IOXMLParser PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;\$<LINK_ONLY:VTK::IOCore>;\$<LINK_ONLY:VTK::expat>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::IOXML
add_library(VTK::IOXML STATIC IMPORTED)

set_target_properties(VTK::IOXML PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonExecutionModel;VTK::IOXMLParser;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::IOCore>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::ImagingSources
add_library(VTK::ImagingSources STATIC IMPORTED)

set_target_properties(VTK::ImagingSources PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonCore>;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::ImagingCore>"
)

# Create imported target VTK::freetype
add_library(VTK::freetype STATIC IMPORTED)

set_target_properties(VTK::freetype PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_LINK_LIBRARIES "VTK::kwiml;VTK::zlib"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::RenderingFreeType
add_library(VTK::RenderingFreeType STATIC IMPORTED)

set_target_properties(VTK::RenderingFreeType PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonExecutionModel;VTK::RenderingCore;VTK::freetype;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::FiltersGeneral>"
)

# Create imported target VTK::ImagingFourier
add_library(VTK::ImagingFourier STATIC IMPORTED)

set_target_properties(VTK::ImagingFourier PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonExecutionModel;VTK::ImagingCore;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::eigen
add_library(VTK::eigen INTERFACE IMPORTED)

set_target_properties(VTK::eigen PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::FiltersStatistics
add_library(VTK::FiltersStatistics STATIC IMPORTED)

set_target_properties(VTK::FiltersStatistics PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::ImagingFourier>;\$<LINK_ONLY:VTK::eigen>"
)

# Create imported target VTK::ParallelCore
add_library(VTK::ParallelCore STATIC IMPORTED)

set_target_properties(VTK::ParallelCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::IOLegacy>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::diy2
add_library(VTK::diy2 INTERFACE IMPORTED)

set_target_properties(VTK::diy2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::ParallelDIY
add_library(VTK::ParallelDIY STATIC IMPORTED)

set_target_properties(VTK::ParallelDIY PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "DIY_NO_THREADS"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::ParallelCore;VTK::diy2;\$<LINK_ONLY:VTK::FiltersGeneral>;\$<LINK_ONLY:VTK::IOXML>"
)

# Create imported target VTK::FiltersExtraction
add_library(VTK::FiltersExtraction STATIC IMPORTED)

set_target_properties(VTK::FiltersExtraction PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonExecutionModel;VTK::FiltersGeneral;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::FiltersCore>;\$<LINK_ONLY:VTK::FiltersStatistics>;\$<LINK_ONLY:VTK::ParallelDIY>"
)

# Create imported target VTK::InfovisCore
add_library(VTK::InfovisCore STATIC IMPORTED)

set_target_properties(VTK::InfovisCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonColor;VTK::IOImage;VTK::ImagingCore;VTK::ImagingSources;VTK::RenderingFreeType;\$<LINK_ONLY:VTK::FiltersExtraction>;\$<LINK_ONLY:VTK::FiltersGeneral>"
)

# Create imported target VTK::libxml2
add_library(VTK::libxml2 STATIC IMPORTED)

set_target_properties(VTK::libxml2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/vtklibxml2/include;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_LINK_LIBRARIES "VTK::zlib"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::IOInfovis
add_library(VTK::IOInfovis STATIC IMPORTED)

set_target_properties(VTK::IOInfovis PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonExecutionModel;VTK::IOLegacy;VTK::IOXML;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::IOCore>;\$<LINK_ONLY:VTK::IOXMLParser>;\$<LINK_ONLY:VTK::InfovisCore>;\$<LINK_ONLY:VTK::libxml2>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::FiltersHybrid
add_library(VTK::FiltersHybrid STATIC IMPORTED)

set_target_properties(VTK::FiltersHybrid PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonTransforms;VTK::FiltersGeometry;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::FiltersCore>;\$<LINK_ONLY:VTK::FiltersGeneral>;\$<LINK_ONLY:VTK::ImagingCore>;\$<LINK_ONLY:VTK::ImagingSources>;\$<LINK_ONLY:VTK::RenderingCore>;\$<LINK_ONLY:VTK::vtksys>"
)

# Create imported target VTK::jsoncpp
add_library(VTK::jsoncpp STATIC IMPORTED)

set_target_properties(VTK::jsoncpp PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0;${_IMPORT_PREFIX}/include/vtk-9.0/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtk-9.0/"
)

# Create imported target VTK::IOGeometry
add_library(VTK::IOGeometry STATIC IMPORTED)

set_target_properties(VTK::IOGeometry PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::IOCore;VTK::IOLegacy;\$<LINK_ONLY:VTK::CommonMisc>;\$<LINK_ONLY:VTK::CommonSystem>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::FiltersGeneral>;\$<LINK_ONLY:VTK::FiltersHybrid>;\$<LINK_ONLY:VTK::ImagingCore>;\$<LINK_ONLY:VTK::IOImage>;\$<LINK_ONLY:VTK::RenderingCore>;\$<LINK_ONLY:VTK::jsoncpp>;\$<LINK_ONLY:VTK::vtksys>;\$<LINK_ONLY:VTK::zlib>"
)

# Create imported target VTK::InteractionStyle
add_library(VTK::InteractionStyle STATIC IMPORTED)

set_target_properties(VTK::InteractionStyle PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonDataModel;VTK::RenderingCore;\$<LINK_ONLY:VTK::CommonCore>;\$<LINK_ONLY:VTK::CommonMath>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::FiltersExtraction>;\$<LINK_ONLY:VTK::FiltersSources>"
)

# Create imported target VTK::FiltersModeling
add_library(VTK::FiltersModeling STATIC IMPORTED)

set_target_properties(VTK::FiltersModeling PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-9.0"
  INTERFACE_LINK_LIBRARIES "VTK::CommonExecutionModel;VTK::CommonMisc;VTK::FiltersGeneral;\$<LINK_ONLY:VTK::CommonCore>;\$<LINK_ONLY:VTK::CommonDataModel>;\$<LINK_ONLY:VTK::CommonTransforms>;\$<LINK_ONLY:VTK::FiltersCore>;\$<LINK_ONLY:VTK::FiltersSources>"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/VTK-targets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
