# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget vtksys vtkCommonCore vtkCommonMath vtkCommonMisc vtkCommonSystem vtkCommonTransforms vtkCommonDataModel vtkCommonColor vtkCommonComputationalGeometry vtkCommonExecutionModel vtkDICOMParser vtkFiltersCore vtkFiltersGeneral vtkImagingCore vtkImagingFourier vtkFiltersStatistics vtkFiltersExtraction vtkFiltersGeometry vtkFiltersSources vtkFiltersModeling vtkdoubleconversion vtklz4 vtklzma vtkzlib vtkIOCore vtkmetaio vtkjpeg vtkpng vtktiff vtkIOImage vtkIOLegacy vtkIOGeometry vtkexpat vtkIOXMLParser vtkIOXML vtkInfovisCore vtklibxml2 vtkIOInfovis vtkIOPLY vtkImagingMath vtkRenderingCore vtkInteractionStyle vtkParallelCore vtkfreetype vtkRenderingFreeType vtkglew vtkRenderingOpenGL2 vtkRenderingVolume vtkRenderingVolumeOpenGL2 vtkTestingRendering)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target vtksys
add_library(vtksys STATIC IMPORTED)

set_target_properties(vtksys PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-8.2"
  INTERFACE_LINK_LIBRARIES "dl"
)

# Create imported target vtkCommonCore
add_library(vtkCommonCore STATIC IMPORTED)

set_target_properties(vtkCommonCore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:vtksys>;\$<LINK_ONLY:log>"
)

# Create imported target vtkCommonMath
add_library(vtkCommonMath STATIC IMPORTED)

set_target_properties(vtkCommonMath PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore"
)

# Create imported target vtkCommonMisc
add_library(vtkCommonMisc STATIC IMPORTED)

set_target_properties(vtkCommonMisc PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonMath;\$<LINK_ONLY:vtksys>"
)

# Create imported target vtkCommonSystem
add_library(vtkCommonSystem STATIC IMPORTED)

set_target_properties(vtkCommonSystem PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;\$<LINK_ONLY:vtksys>"
)

# Create imported target vtkCommonTransforms
add_library(vtkCommonTransforms STATIC IMPORTED)

set_target_properties(vtkCommonTransforms PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonMath"
)

# Create imported target vtkCommonDataModel
add_library(vtkCommonDataModel STATIC IMPORTED)

set_target_properties(vtkCommonDataModel PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonMath;vtkCommonTransforms;\$<LINK_ONLY:vtkCommonMisc>;\$<LINK_ONLY:vtkCommonSystem>;\$<LINK_ONLY:vtksys>"
)

# Create imported target vtkCommonColor
add_library(vtkCommonColor STATIC IMPORTED)

set_target_properties(vtkCommonColor PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel"
)

# Create imported target vtkCommonComputationalGeometry
add_library(vtkCommonComputationalGeometry STATIC IMPORTED)

set_target_properties(vtkCommonComputationalGeometry PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel"
)

# Create imported target vtkCommonExecutionModel
add_library(vtkCommonExecutionModel STATIC IMPORTED)

set_target_properties(vtkCommonExecutionModel PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel;\$<LINK_ONLY:vtkCommonMisc>;\$<LINK_ONLY:vtkCommonSystem>"
)

# Create imported target vtkDICOMParser
add_library(vtkDICOMParser STATIC IMPORTED)

set_target_properties(vtkDICOMParser PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
)

# Create imported target vtkFiltersCore
add_library(vtkFiltersCore STATIC IMPORTED)

set_target_properties(vtkFiltersCore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;vtkCommonMisc;\$<LINK_ONLY:vtkCommonMath>;\$<LINK_ONLY:vtkCommonSystem>;\$<LINK_ONLY:vtkCommonTransforms>"
)

# Create imported target vtkFiltersGeneral
add_library(vtkFiltersGeneral STATIC IMPORTED)

set_target_properties(vtkFiltersGeneral PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;vtkCommonMisc;vtkFiltersCore;\$<LINK_ONLY:vtkCommonComputationalGeometry>;\$<LINK_ONLY:vtkCommonMath>;\$<LINK_ONLY:vtkCommonSystem>;\$<LINK_ONLY:vtkCommonTransforms>"
)

# Create imported target vtkImagingCore
add_library(vtkImagingCore STATIC IMPORTED)

set_target_properties(vtkImagingCore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;\$<LINK_ONLY:vtkCommonMath>;\$<LINK_ONLY:vtkCommonTransforms>"
)

# Create imported target vtkImagingFourier
add_library(vtkImagingFourier STATIC IMPORTED)

set_target_properties(vtkImagingFourier PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonExecutionModel;vtkImagingCore;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtksys>"
)

# Create imported target vtkFiltersStatistics
add_library(vtkFiltersStatistics STATIC IMPORTED)

set_target_properties(vtkFiltersStatistics PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonExecutionModel;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtkCommonMisc>;\$<LINK_ONLY:vtkImagingFourier>"
)

# Create imported target vtkFiltersExtraction
add_library(vtkFiltersExtraction STATIC IMPORTED)

set_target_properties(vtkFiltersExtraction PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonExecutionModel;vtkFiltersGeneral;\$<LINK_ONLY:vtkCommonCore>;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtkFiltersCore>;\$<LINK_ONLY:vtkFiltersStatistics>"
)

# Create imported target vtkFiltersGeometry
add_library(vtkFiltersGeometry STATIC IMPORTED)

set_target_properties(vtkFiltersGeometry PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;\$<LINK_ONLY:vtkFiltersCore>"
)

# Create imported target vtkFiltersSources
add_library(vtkFiltersSources STATIC IMPORTED)

set_target_properties(vtkFiltersSources PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonDataModel;vtkCommonExecutionModel;\$<LINK_ONLY:vtkCommonComputationalGeometry>;\$<LINK_ONLY:vtkCommonCore>;\$<LINK_ONLY:vtkCommonTransforms>;\$<LINK_ONLY:vtkFiltersCore>;\$<LINK_ONLY:vtkFiltersGeneral>"
)

# Create imported target vtkFiltersModeling
add_library(vtkFiltersModeling STATIC IMPORTED)

set_target_properties(vtkFiltersModeling PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonExecutionModel;vtkCommonMisc;vtkFiltersGeneral;\$<LINK_ONLY:vtkCommonCore>;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtkCommonTransforms>;\$<LINK_ONLY:vtkFiltersCore>;\$<LINK_ONLY:vtkFiltersSources>"
)

# Create imported target vtkdoubleconversion
add_library(vtkdoubleconversion STATIC IMPORTED)

set_target_properties(vtkdoubleconversion PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtk-8.2"
)

# Create imported target vtklz4
add_library(vtklz4 STATIC IMPORTED)

set_target_properties(vtklz4 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
)

# Create imported target vtklzma
add_library(vtklzma STATIC IMPORTED)

set_target_properties(vtklzma PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
)

# Create imported target vtkzlib
add_library(vtkzlib STATIC IMPORTED)

set_target_properties(vtkzlib PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
)

# Create imported target vtkIOCore
add_library(vtkIOCore STATIC IMPORTED)

set_target_properties(vtkIOCore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonExecutionModel;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtkCommonMisc>;\$<LINK_ONLY:vtklz4>;\$<LINK_ONLY:vtklzma>;\$<LINK_ONLY:vtksys>;\$<LINK_ONLY:vtkzlib>;\$<LINK_ONLY:vtkdoubleconversion>"
)

# Create imported target vtkmetaio
add_library(vtkmetaio STATIC IMPORTED)

set_target_properties(vtkmetaio PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkzlib"
)

# Create imported target vtkjpeg
add_library(vtkjpeg STATIC IMPORTED)

set_target_properties(vtkjpeg PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
)

# Create imported target vtkpng
add_library(vtkpng STATIC IMPORTED)

set_target_properties(vtkpng PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:vtkzlib>;\$<LINK_ONLY:m>"
)

# Create imported target vtktiff
add_library(vtktiff STATIC IMPORTED)

set_target_properties(vtktiff PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:vtkjpeg>;\$<LINK_ONLY:vtkzlib>"
)

# Create imported target vtkIOImage
add_library(vtkIOImage STATIC IMPORTED)

set_target_properties(vtkIOImage PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonExecutionModel;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtkCommonMath>;\$<LINK_ONLY:vtkCommonMisc>;\$<LINK_ONLY:vtkCommonSystem>;\$<LINK_ONLY:vtkCommonTransforms>;\$<LINK_ONLY:vtkDICOMParser>;\$<LINK_ONLY:vtkmetaio>;\$<LINK_ONLY:vtkjpeg>;\$<LINK_ONLY:vtkpng>;\$<LINK_ONLY:vtksys>;\$<LINK_ONLY:vtktiff>;\$<LINK_ONLY:vtkzlib>"
)

# Create imported target vtkIOLegacy
add_library(vtkIOLegacy STATIC IMPORTED)

set_target_properties(vtkIOLegacy PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;vtkIOCore;\$<LINK_ONLY:vtkCommonMisc>;\$<LINK_ONLY:vtksys>"
)

# Create imported target vtkIOGeometry
add_library(vtkIOGeometry STATIC IMPORTED)

set_target_properties(vtkIOGeometry PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonDataModel;vtkCommonExecutionModel;vtkIOCore;vtkIOLegacy;\$<LINK_ONLY:vtkCommonCore>;\$<LINK_ONLY:vtkCommonMisc>;\$<LINK_ONLY:vtkCommonSystem>;\$<LINK_ONLY:vtkCommonTransforms>;\$<LINK_ONLY:vtkIOImage>;\$<LINK_ONLY:vtksys>;\$<LINK_ONLY:vtkzlib>"
)

# Create imported target vtkexpat
add_library(vtkexpat STATIC IMPORTED)

set_target_properties(vtkexpat PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
)

# Create imported target vtkIOXMLParser
add_library(vtkIOXMLParser STATIC IMPORTED)

set_target_properties(vtkIOXMLParser PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel;\$<LINK_ONLY:vtkIOCore>;\$<LINK_ONLY:vtkexpat>;\$<LINK_ONLY:vtksys>"
)

# Create imported target vtkIOXML
add_library(vtkIOXML STATIC IMPORTED)

set_target_properties(vtkIOXML PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonExecutionModel;vtkIOXMLParser;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtkCommonMisc>;\$<LINK_ONLY:vtkCommonSystem>;\$<LINK_ONLY:vtkIOCore>;\$<LINK_ONLY:vtksys>"
)

# Create imported target vtkInfovisCore
add_library(vtkInfovisCore STATIC IMPORTED)

set_target_properties(vtkInfovisCore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;\$<LINK_ONLY:vtkFiltersExtraction>;\$<LINK_ONLY:vtkFiltersGeneral>"
)

# Create imported target vtklibxml2
add_library(vtklibxml2 STATIC IMPORTED)

set_target_properties(vtklibxml2 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkzlib;dl;dl;m"
)

# Create imported target vtkIOInfovis
add_library(vtkIOInfovis STATIC IMPORTED)

set_target_properties(vtkIOInfovis PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonExecutionModel;vtkIOLegacy;vtkIOXML;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtkCommonMisc>;\$<LINK_ONLY:vtkIOCore>;\$<LINK_ONLY:vtkIOXMLParser>;\$<LINK_ONLY:vtkInfovisCore>;\$<LINK_ONLY:vtklibxml2>;\$<LINK_ONLY:vtksys>"
)

# Create imported target vtkIOPLY
add_library(vtkIOPLY STATIC IMPORTED)

set_target_properties(vtkIOPLY PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkIOCore;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtkCommonMisc>;\$<LINK_ONLY:vtksys>"
)

# Create imported target vtkImagingMath
add_library(vtkImagingMath STATIC IMPORTED)

set_target_properties(vtkImagingMath PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonExecutionModel;\$<LINK_ONLY:vtkCommonCore>;\$<LINK_ONLY:vtkCommonDataModel>"
)

# Create imported target vtkRenderingCore
add_library(vtkRenderingCore STATIC IMPORTED)

set_target_properties(vtkRenderingCore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;vtkCommonMath;vtkFiltersCore;\$<LINK_ONLY:vtkCommonColor>;\$<LINK_ONLY:vtkCommonComputationalGeometry>;\$<LINK_ONLY:vtkCommonSystem>;\$<LINK_ONLY:vtkCommonTransforms>;\$<LINK_ONLY:vtkFiltersGeneral>;\$<LINK_ONLY:vtkFiltersGeometry>;\$<LINK_ONLY:vtkFiltersSources>;\$<LINK_ONLY:vtksys>"
)

# Create imported target vtkInteractionStyle
add_library(vtkInteractionStyle STATIC IMPORTED)

set_target_properties(vtkInteractionStyle PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonDataModel;vtkRenderingCore;vtkRenderingCore;\$<LINK_ONLY:vtkCommonCore>;\$<LINK_ONLY:vtkCommonMath>;\$<LINK_ONLY:vtkCommonTransforms>;\$<LINK_ONLY:vtkFiltersExtraction>;\$<LINK_ONLY:vtkFiltersSources>"
)

# Create imported target vtkParallelCore
add_library(vtkParallelCore STATIC IMPORTED)

set_target_properties(vtkParallelCore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtkCommonSystem>;\$<LINK_ONLY:vtkIOLegacy>;\$<LINK_ONLY:vtksys>"
)

# Create imported target vtkfreetype
add_library(vtkfreetype STATIC IMPORTED)

set_target_properties(vtkfreetype PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkzlib"
)

# Create imported target vtkRenderingFreeType
add_library(vtkRenderingFreeType STATIC IMPORTED)

set_target_properties(vtkRenderingFreeType PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonExecutionModel;vtkRenderingCore;vtkRenderingCore;vtkfreetype;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtkFiltersGeneral>"
)

# Create imported target vtkglew
add_library(vtkglew STATIC IMPORTED)

set_target_properties(vtkglew PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "GLEW_STATIC"
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
)

# Create imported target vtkRenderingOpenGL2
add_library(vtkRenderingOpenGL2 STATIC IMPORTED)

set_target_properties(vtkRenderingOpenGL2 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel;vtkRenderingCore;vtkRenderingCore;\$<LINK_ONLY:vtkCommonExecutionModel>;\$<LINK_ONLY:vtkCommonMath>;\$<LINK_ONLY:vtkCommonSystem>;\$<LINK_ONLY:vtkCommonTransforms>;\$<LINK_ONLY:vtkglew>;\$<LINK_ONLY:vtksys>;/home/tk/Downloads/android-ndk-r16b/platforms/android-24/arch-x86_64/usr/lib64/libEGL.so;\$<LINK_ONLY:android>"
)

# Create imported target vtkRenderingVolume
add_library(vtkRenderingVolume STATIC IMPORTED)

set_target_properties(vtkRenderingVolume PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonExecutionModel;vtkRenderingCore;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtkCommonMath>;\$<LINK_ONLY:vtkCommonMisc>;\$<LINK_ONLY:vtkCommonSystem>;\$<LINK_ONLY:vtkCommonTransforms>;\$<LINK_ONLY:vtkIOXML>;\$<LINK_ONLY:vtkImagingCore>"
)

# Create imported target vtkRenderingVolumeOpenGL2
add_library(vtkRenderingVolumeOpenGL2 STATIC IMPORTED)

set_target_properties(vtkRenderingVolumeOpenGL2 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel;vtkImagingCore;vtkImagingMath;vtkRenderingCore;vtkRenderingOpenGL2;vtkRenderingVolume;vtkRenderingVolume;vtkglew;\$<LINK_ONLY:vtkCommonMath>;\$<LINK_ONLY:vtkCommonSystem>;\$<LINK_ONLY:vtkCommonTransforms>;\$<LINK_ONLY:vtkFiltersCore>;\$<LINK_ONLY:vtkFiltersGeneral>;\$<LINK_ONLY:vtkFiltersSources>;\$<LINK_ONLY:vtksys>"
)

# Create imported target vtkTestingRendering
add_library(vtkTestingRendering STATIC IMPORTED)

set_target_properties(vtkTestingRendering PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkRenderingCore;vtkCommonCore;\$<LINK_ONLY:vtkCommonDataModel>;\$<LINK_ONLY:vtkCommonExecutionModel>;\$<LINK_ONLY:vtkCommonSystem>;\$<LINK_ONLY:vtkIOImage>;\$<LINK_ONLY:vtkImagingCore>;\$<LINK_ONLY:vtksys>"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/VTKTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
