# Generated by Django 3.1.5 on 2021-02-05 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210122_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relation',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Doctor'), ('2', 'Patient')], default='2', max_length=10),
        ),
    ]
